In [1]:
# import
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sentence_transformers import SentenceTransformer
import umap
import hdbscan
import warnings

from training_pipeline import train_clustering_pipeline, save_clustering_model, load_clustering_model, FeatureTransformer

warnings.filterwarnings('ignore')

c:\Users\Yaseen T P\Desktop\Gordian Redis system\gorenv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

#### Train model

In [2]:
# prepare dataset
source = 'metals4u.co'
sample_data = pd.read_excel("../dataset/materials.xlsx")
sample_data = sample_data[sample_data['Source\n']==source]
sample_data.rename(columns={'Unit\n':'Unit',"Rate £":"Rate"},inplace=True)
train_dataset = sample_data
inference_dataset = sample_data[-4:]

In [3]:
sample_data.columns

Index(['Unnamed: 0', 'Code', 'Code.1', 'Description', 'Type', 'Unit', 'Rate',
       'Extracted Price', 'New Rate (ex VAT)', 'New Rate INCL VAT)',
       '% change', 'Discount', 'Wastage', 'Cost Code', 'Supplier Code',
       'Supplier', 'URL', 'Comments', 'Source\n', 'Web', 'Status',
       'Unnamed: 21', 'InApp Comment'],
      dtype='object')

In [4]:
    
# Train the pipeline
clustered = train_clustering_pipeline(train_dataset, preference='permissive')
    
# Display results
print("\nSample of clustered data:")
print(clustered['df_clustered'][['Description', 'Unit', 'Rate', 'cluster_type', 'cluster_probability']].head(10))
clustered['df_clustered'].to_excel("cluster_result.xlsx", index=False)

============================================================
HDBSCAN CLUSTERING TRAINING PIPELINE
============================================================
Dataset size: 22 samples
Preference: permissive

Step 1: Feature Transformation
----------------------------------------

Batches: 100%|██████████| 1/1 [00:00<00:00,  1.86it/s]

Text embeddings shape: (22, 384)
Categorical encoded shape: (22, 4)
Numerical scaled shape: (22, 1)

Step 2: UMAP Dimensionality Reduction
----------------------------------------
UMAP reduced shape: (22, 15)

Step 3: Calculate HDBSCAN Parameters
----------------------------------------
min_cluster_size: 3
min_samples: 2
Ratio (min_samples/min_cluster_size): 0.67

Step 4: HDBSCAN Clustering
----------------------------------------
Number of clusters found: 2
Number of outliers: 0 (0.0%)

Step 5: Computing Cluster Profiles
----------------------------------------
Cluster 0: 8 members, threshold=0.8915
Cluster 1: 14 members, threshold=1.0719

Step 6: Adding cluster labels to dataframe
----------------------------------------
hi

Sample of clustered data:
                                           Description Unit     Rate  \
192      High Yield bar reinforcement (Grade 500) 25mm    t  3923.40
193      High Yield bar reinforcement (Grade 500) 20mm    t  3178.98
194      High Yield bar reinforcement (Grade 500) 16mm    t  3138.30
195      High Yield bar reinforcement (Grade 500) 12mm    t  3558.16
196      High Yield bar reinforcement (Grade 500) 10mm    t  4043.76
197       High Yield bar reinforcement (Grade 500) 8mm    t  4836.12
249                 Mild Steel 6 x 25mm flat arch bars    m     3.45
250                 Mild Steel 6 x 30mm flat arch bars    m     3.95
343  10mm Diameter 316 Stainless Steel Round Bar x ...   nr     5.97
344  20mm Diameter 316 Stainless Steel Round Bar x ...   nr    32.00

     cluster_type  cluster_probability
192             0             0.941023
193             0             1.000000
194             0             0.721910
195             0             0.936216
196             0             0.902659
197             0             0.941023
249             1             1.000000
250             1             1.000000
343             1             1.000000
344             1             0.975033

In [5]:
clustered['df_clustered']

,Unnamed: 0,Code,Code.1,Description,Type,Unit,Rate,Extracted Price,New Rate (ex VAT),New Rate INCL VAT),...,URL,Comments,Source\n,Web,Status,Unnamed: 21,InApp Comment,cluster_type,cluster_probability,confidence
192,NaN,BME4001,BME4001,High Yield bar reinforcement (Grade 500) 25mm,1.0,t,3923.40,NaN,NaN,NaN,...,https://www.metals4u.co.uk/shop-by-application...,260 meters per ton x cost per metre (note 24mm...,metals4u.co,Yes,NaN,NaN,NaN,0,0.941023,1.282601e-01
193,NaN,BME4002,BME4002,High Yield bar reinforcement (Grade 500) 20mm,1.0,t,3178.98,NaN,NaN,NaN,...,https://www.metals4u.co.uk/shop-by-application...,406 metres per ton x cost per metre 20mm ...,metals4u.co,Yes,NaN,NaN,NaN,0,1.000000,1.000000e+00
194,NaN,BME4003,BME4003,High Yield bar reinforcement (Grade 500) 16mm,1.0,t,3138.30,NaN,NaN,NaN,...,https://www.metals4u.co.uk/shop-by-application...,634 metres per ton x cost per metre 16mm ...,metals4u.co,Yes,NaN,NaN,NaN,0,0.721910,0.000000e+00
195,NaN,BME4004,BME4004,High Yield bar reinforcement (Grade 500) 12mm,1.0,t,3558.16,NaN,NaN,NaN,...,https://www.metals4u.co.uk/shop-by-application...,1126 metres per ton x cost per metre 12mm ...,metals4u.co,Yes,NaN,NaN,NaN,0,0.936216,3.650361e-01
196,NaN,BME4005,BME4005,High Yield bar reinforcement (Grade 500) 10mm,1.0,t,4043.76,NaN,NaN,NaN,...,https://www.metals4u.co.uk/shop-by-application...,1624 metres per ton x cost per metre 10mm ...,metals4u.co,Yes,NaN,NaN,NaN,0,0.902659,2.940473e-01
197,NaN,BME4006,BME4006,High Yield bar reinforcement (Grade 500) 8mm,1.0,t,4836.12,NaN,NaN,NaN,...,https://www.metals4u.co.uk/shop-by-application...,2532 metres per ton x cost per metre 8mm ...,metals4u.co,Yes,NaN,NaN,NaN,0,0.941023,1.909512e-02
249,NaN,BMF12002,BMF12002,Mild Steel 6 x 25mm flat arch bars,2.0,m,3.45,NaN,NaN,NaN,...,https://www.metals4u.co.uk/materials/mild-stee...,price per m May 24 ce updates £3.45 exc ...,metals4u.co,Yes,NaN,NaN,NaN,1,1.000000,1.937293e-01
250,NaN,BMF12003,BMF12003,Mild Steel 6 x 30mm flat arch bars,2.0,m,3.95,NaN,NaN,NaN,...,https://www.metals4u.co.uk/materials/mild-stee...,price per m May 24 ce updates £3.95 exc ...,metals4u.co,Yes,NaN,NaN,NaN,1,1.000000,2.004335e-01
343,NaN,BMF15003,BMF15003,10mm Diameter 316 Stainless Steel Round Bar x ...,NaN,nr,5.97,NaN,NaN,NaN,...,https://www.metals4u.co.uk/materials/stainless...,price each nr use calculate box for pricing 5...,metals4u.co,Yes,NaN,NaN,NaN,1,1.000000,1.000000e+00
344,NaN,BMF15004,BMF15004,20mm Diameter 316 Stainless Steel Round Bar x ...,NaN,nr,32.00,NaN,NaN,NaN,...,https://www.metals4u.co.uk/materials/stainless...,price each nr use calculate box for pricing 5...,metals4u.co,Yes,NaN,NaN,NaN,1,0.975033,1.095623e-02
451,NaN,BMG1001,BMG1001,203 x 133 x 25 kg/m Universal beams.,NaN,t,3160.00,NaN,3160.00,NaN,...,https://www.metals4u.co.uk/shop-by-application...,Based on 1m beam price £93.58 ex vat 22.3.23 ...,metals4u.co,Yes,NaN,NaN,NaN,0,1.000000,3.311592e-01
452,NaN,BMG1002,BMG1002,203 x 203 x 46 kg/m Universal beams.,NaN,t,4565.22,NaN,4565.22,NaN,...,https://www.metals4u.co.uk/shop-by-application...,price tonne (1000 divided by kg per metre = 4...,metals4u.co,Yes,NaN,NaN,NaN,0,1.000000,8.792621e-02
453,NaN,BMG1003,BMG1003,Steel plate 3mm,NaN,m2,59.95,NaN,NaN,NaN,...,https://www.metals4u.co.uk/materials/mild-stee...,May24 ce update no change added url prcced per m,metals4u.co,Yes,NaN,NaN,NaN,1,1.000000,1.593756e-01
454,NaN,BMG1004,BMG1004,Steel equal angle 25mm x 3mm thick,NaN,m,3.49,NaN,NaN,NaN,...,https://www.metals4u.co.uk/materials/mild-stee...,May 24 ce update added url priced per m,metals4u.co,Yes,NaN,NaN,NaN,1,1.000000,1.623803e-01
1905,NaN,BMP2008,BMP2008,Black mild steel round bar 25mm,NaN,m,9.99,NaN,NaN,NaN,...,https://www.metals4u.co.uk/materials/mild-stee...,May24 ce update added url priced per m,metals4u.co,Yes,NaN,NaN,NaN,1,1.000000,1.571285e-01
2121,NaN,BMP26001,BMP26001,Galvanised mild steel waterbars 3 x 30mm,NaN,m,7.04,NaN,NaN,NaN,...,https://www.metals4u.co.uk/materials/mild-stee...,May 24 ce update exc vat added url priced pe...,metals4u.co,Yes,NaN,NaN,NaN,1,1.000000,1.060236e-01
2122,NaN,BMP26002,BMP26002,Galvanised mild steel waterbars 3 x 50mm,NaN,m,8.65,NaN,NaN,NaN,...,https://www.metals4u.co.uk/materials/mild-stee...,May 24 ce update previous price entered look ...,metals4u.co,Yes,NaN,NaN,NaN,1,0.959714,6.990671e-02
3743,NaN,19010755,19010755,Threaded Rod M6,NaN,m,1.32,NaN,1.32,NaN,...,https://www.metals4u.co.uk/fixtures-fittings/f...,Mar 24 ce updates no changes,metals4u.co,Yes,NaN,NaN,NaN,1,1.000000,1.669722e-01
3744,NaN,19010766,19010766,Threaded Rod M8,NaN,m,1.75,NaN,1.75,NaN,...,https://www.metals4u.co.uk/fixtures-fittings/f...,https://www.metals4u.co.uk/fixtures-fittings/f...,metals4u.co,Yes,NaN,NaN,NaN,1,1.000000,9.633154e-02
3745,NaN,19010777,19010777,Threaded Rod M10,NaN,m,2.77,NaN,NaN,NaN,...,https://www.metals4u.co.uk/fixtures-fittings/f...,https://www.metals4u.co.uk/fixtures-fittings/f...,metals4u.co,Yes,NaN,NaN,NaN,1,1.000000,5.313814e-02
3746,NaN,19010788,19010788,Threaded Rod M12,NaN,m,4.30,NaN,NaN,NaN,...,https://www.metals4u.co.uk/fixtures-fittings/f...,https://www.metals4u.co.uk/fixtures-fittings/f...,metals4u.co,Yes,NaN,NaN,NaN,1,1.000000,2.058003e-01
4185,NaN,308889,308889,40 x 40 x 6mm Angle Iron,NaN,m,8.45,NaN,NaN,NaN,...,https://www.metals4u.co.uk/materials/mild-stee...,Price decrease Mar 24 ce,metals4u.co,Yes,NaN,NaN,NaN,1,0.981198,-1.192093e-07

#### Save and load cluster model

In [6]:
save_clustering_model(clustered, 'metals4u_model1')

============================================================
SAVING CLUSTERING MODEL
============================================================
Save directory: c:\Users\Yaseen T P\Desktop\Gordian Redis system\item_clustering\metals4u_model1

1. Saving Feature Transformer...
   ✓ Saved to feature_transformer.joblib
2. Saving UMAP Model...
   ✓ Saved to umap_model.joblib
3. Saving HDBSCAN Model...
   ✓ Saved to hdbscan_model.joblib
4. Saving Cluster Profiles...
   ✓ Saved to cluster_profiles.json
5. Saving Metadata...
   ✓ Saved to metadata.json
6. Saving Clustered Data (optional)...
   ✓ Saved to clustered_data.csv

============================================================
✓ ALL MODELS SAVED SUCCESSFULLY
============================================================
Total files saved: 6
Directory size: 89319.71 KB

{'feature_transformer': 'metals4u_model1\\feature_transformer.joblib',
 'umap_model': 'metals4u_model1\\umap_model.joblib',
 'hdbscan_model': 'metals4u_model1\\hdbscan_model.joblib',
 'cluster_profiles': 'metals4u_model1\\cluster_profiles.json',
 'metadata': 'metals4u_model1\\metadata.json',
 'clustered_data': 'metals4u_model1\\clustered_data.csv'}

In [7]:
model = load_clustering_model("metals4u_model1")

============================================================
LOADING CLUSTERING MODEL
============================================================
Load directory: c:\Users\Yaseen T P\Desktop\Gordian Redis system\item_clustering\metals4u_model1

1. Loading Feature Transformer...
   ✓ Loaded from feature_transformer.joblib
2. Loading UMAP Model...
   ✓ Loaded from umap_model.joblib
3. Loading HDBSCAN Model...
   ✓ Loaded from hdbscan_model.joblib
4. Loading Cluster Profiles...
   ✓ Loaded 2 cluster profiles
5. Loading Metadata...
   ✓ Loaded metadata
      - Clusters: 2
      - Outlier rate: 0.0%

============================================================
✓ ALL MODELS LOADED SUCCESSFULLY
============================================================

#### Inference

In [15]:
from inference_pipeline import predict_batch
results = predict_batch(inference_dataset, model, confidence_threshold=0.5)

# 4. Use the results
print(results[['Description', 'predicted_cluster', 'confidence']])

============================================================
INFERENCE PIPELINE - BATCH PREDICTION
============================================================
Number of items to classify: 4
Confidence threshold: 0.5

Step 1: Feature Transformation
----------------------------------------
Transformed shape: (4, 389)

Step 2: UMAP Projection
----------------------------------------
UMAP shape: (4, 15)

Step 3: Cluster Prediction
----------------------------------------
✓ Predictions complete
  Assigned to clusters: 0 (0.0%)
  Flagged as outliers: 4 (100.0%)

============================================================
INFERENCE COMPLETE
============================================================

                   Description  predicted_cluster  confidence
3744           Threaded Rod M8                 -1   -0.529971
3745          Threaded Rod M10                 -1   -0.500199
3746          Threaded Rod M12                 -1   -0.483442
4185  40 x 40 x 6mm Angle Iron                 -1   -0.488913

In [16]:
results

,Unnamed: 0,Code,Code.1,Description,Type,Unit,Rate,Extracted Price,New Rate (ex VAT),New Rate INCL VAT),...,Comments,Source\n,Web,Status,Unnamed: 21,InApp Comment,predicted_cluster,confidence,nearest_cluster,distance
3744,NaN,19010766,19010766,Threaded Rod M8,NaN,m,1.75,NaN,1.75,NaN,...,https://www.metals4u.co.uk/fixtures-fittings/f...,metals4u.co,Yes,NaN,NaN,NaN,-1,-0.529971,1,1.640028
3745,NaN,19010777,19010777,Threaded Rod M10,NaN,m,2.77,NaN,NaN,NaN,...,https://www.metals4u.co.uk/fixtures-fittings/f...,metals4u.co,Yes,NaN,NaN,NaN,-1,-0.500199,1,1.608115
3746,NaN,19010788,19010788,Threaded Rod M12,NaN,m,4.30,NaN,NaN,NaN,...,https://www.metals4u.co.uk/fixtures-fittings/f...,metals4u.co,Yes,NaN,NaN,NaN,-1,-0.483442,1,1.590152
4185,NaN,308889,308889,40 x 40 x 6mm Angle Iron,NaN,m,8.45,NaN,NaN,NaN,...,Price decrease Mar 24 ce,metals4u.co,Yes,NaN,NaN,NaN,-1,-0.488913,1,1.596017

In [10]:
clustered['df_clustered'].columns

Index(['Unnamed: 0', 'Code', 'Code.1', 'Description', 'Type', 'Unit', 'Rate',
       'Extracted Price', 'New Rate (ex VAT)', 'New Rate INCL VAT)',
       '% change', 'Discount', 'Wastage', 'Cost Code', 'Supplier Code',
       'Supplier', 'URL', 'Comments', 'Source\n', 'Web', 'Status',
       'Unnamed: 21', 'InApp Comment', 'cluster_type', 'cluster_probability',
       'confidence'],
      dtype='object')

In [11]:
print(clustered['df_clustered'][['Description', 'cluster_type','cluster_probability', 'confidence']].tail(4))
# If cluster_type = -1 for these rows → they were never in a cluster
# so no medoid will ever be close enough

                   Description  cluster_type  cluster_probability  \
3744           Threaded Rod M8             1             1.000000
3745          Threaded Rod M10             1             1.000000
3746          Threaded Rod M12             1             1.000000
4185  40 x 40 x 6mm Angle Iron             1             0.981198

        confidence
3744  9.633154e-02
3745  5.313814e-02
3746  2.058003e-01
4185 -1.192093e-07

In [12]:
# In your notebook
X_tr = model['feature_transformer'].transform(inference_dataset)
X_umap_inf = model['umap_model'].transform(X_tr)

# Get the same rows from training UMAP
train_indices = [list(train_dataset.index).index(i) for i in inference_dataset.index]
X_umap_train = model['umap_model'].embedding_[train_indices]

print("Training UMAP coords:", X_umap_train[0][:5])
print("Inference UMAP coords:", X_umap_inf[0][:5])

Training UMAP coords: [ 8.882462   4.2931237 -4.6260247  2.3403213  3.3630664]
Inference UMAP coords: [ 9.172151   4.44434   -4.3093166  2.3867285  3.4238853]